# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: supabase
pluginDownloadUrl: github://api.github.com/LuxChanLu

types:
  supabase:index:Plan:
    type: string
    enum: 
      - name: Free
        value: free
      - name: Pro
        value: pro
  supabase:index:Region:
    type: string
    enum: 
      - name: UsEast1
        value: us-east-1
      - name: UsWest1
        value: us-west-1
      - name: ApSoutheast1
        value: ap-southeast-1
      - name: ApNortheast1
        value: ap-northeast-1
      - name: ApNortheast2
        value: ap-northeast-2
      - name: ApSoutheast2
        value: ap-southeast-2
      - name: EuWest1
        value: eu-west-1
      - name: EuWest2
        value: eu-west-2
      - name: EuCentral1
        value: eu-central-1
      - name: CaCentral1
        value: ca-central-1
      - name: ApSouth1
        value: ap-south-1
      - name: SaEast1
        value: sa-east-1
  supabase:index:FunctionStatus:
    type: string
    enum: 
      - name: Active
        value: ACTIVE
      - name: Removed
        value: REMOVED
      - name: Throttled
        value: THROTTLED

resources:
  supabase:index:Organization:
    inputProperties:
      name:
        type: string
        description: Name of the organization
    requiredInputs:
      - name
    properties:
      name:
        type: string
        description: Name of the organization
    required:
      - name

  supabase:index:Project:
    inputProperties:
      name:
        type: string
        description: Name of the project
      organization_id:
        type: string
        description: Organization ID of the project
      db_pass:
        type: string
        description: Postgres password of the project
        secret: true
        replaceOnChanges: true
      plan:
        type: enum
        $ref: "#/types/supabase:index:Plan"
        description: Plan of the project
      region:
        type: enum
        $ref: "#/types/supabase:index:Region"
        description: Region of the project
        replaceOnChanges: true
      kps_enabled:
        type: boolean
        description: KPS Enabled on the project
    requiredInputs:
      - name
      - organization_id
      - db_pass
      - plan
      - region
      - kps_enabled
    properties:
      organization_id:
        type: string
        description: Organization ID of the project
      name:
        type: string
        description: Name of the project
      region:
        type: enum
        $ref: "#/types/supabase:index:Region"
        description: Region of the project
      created_at:
        type: string
        description: Project creation date
      dbUsername:
        type: string
        description: DB Username
      dbHost:
        type: string
        description: DB Hostname
      dbPort:
        type: integer
        description: DB Port
      dbName:
        type: string
        description: DB Name
      dbPoolingPort:
        type: integer
        description: DB Port for pooled connection
      endpoint:
        type: string
        description: Supabase endpoint for client
    required:
      - name
      - organization_id
      - region
      - created_at
      - dbUsername
      - dbHost
      - dbPort
      - dbName
      - dbPoolingPort
      - endpoint

  supabase:index:Function:
    inputProperties:
      projectId:
        type: string
        description: ID of the project
      name:
        type: string
        description: Name of the function
      slug:
        type: string
        description: Slug of the function
      body:
        type: string
        description: Body of the functino
        secret: true
      verify_jwt:
        type: boolean
        description: Verify JWT before running
        default: false
    requiredInputs:
      - projectId
      - name
      - slug
      - body
    properties:
      name:
        type: string
        description: Name of the function
      slug:
        type: string
        description: Slug of the function
      status:
        type: enum
        $ref: "#/types/supabase:index:FunctionStatus"
        description: Status of the function
      version:
        type: integer
        description: Version of the function
      created_at:
        type: string
        description: Function creation date
      updatedAt:
        type: string
        description: Function updated date
      verify_jwt:
        type: boolean
        description: Verify JWT before running
    required:
      - name
      - slug
      - status
      - version
      - created_at
      - updatedAt
      - verify_jwt

  supabase:index:Secret:
    inputProperties:
      projectId:
        type: string
        description: ID of the project
      name:
        type: string
        description: Name of the secret
      value:
        type: string
        description: Value of the secret
        secret: true
    requiredInputs:
      - projectId
      - name
      - value
    properties:
      name:
        type: string
        description: Name of the secret
      value:
        type: string
        description: Value of the secret
        secret: true
    required:
      - name
      - value

functions:
  supabase:index:GetTypeScript: 
    inputs:
      properties:
        projectId:
          type: string
          description: ID of the project
        includedSchemas:
          type: string
          description: Included schemas
          default: ""
    required:
      - projectId
    outputs:
      properties:
        types:
          type: string
          description: TypeScript types of the project
      required:
        - types

config:
  variables:
    server:
      type: string
      description: Supabase server (https://api.supabase.com/)
      default: https://api.supabase.com/
    token:
      type: string
      description: Supabase auth token
      secret: true

language:
  csharp:
    packageReferences:
      Pulumi: 3.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/LuxChanLu/pulumi-supabase/sdk/go/supabase
  nodejs:
    dependencies:
      "@pulumi/pulumi": "^3.45.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
