// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getTypeScript(args?: GetTypeScriptArgs, opts?: pulumi.InvokeOptions): Promise<GetTypeScriptResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("supabase:project:GetTypeScript", {
        "projectId": args.projectId,
    }, opts);
}

export interface GetTypeScriptArgs {
    /**
     * ID of the project
     */
    projectId?: string;
}

export interface GetTypeScriptResult {
    /**
     * TypeScript types of the project
     */
    readonly types: string;
}

export function getTypeScriptOutput(args?: GetTypeScriptOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTypeScriptResult> {
    return pulumi.output(args).apply(a => getTypeScript(a, opts))
}

export interface GetTypeScriptOutputArgs {
    /**
     * ID of the project
     */
    projectId?: pulumi.Input<string>;
}
