// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./function";
export * from "./getTypeScript";
export * from "./secret";

// Import resources to register:
import { Function } from "./function";
import { Secret } from "./secret";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "supabase:project:Function":
                return new Function(name, <any>undefined, { urn })
            case "supabase:project:Secret":
                return new Secret(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("supabase", "project", _module)
