// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Supabase.Project
{
    public static class GetTypeScript
    {
        public static Task<GetTypeScriptResult> InvokeAsync(GetTypeScriptArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetTypeScriptResult>("supabase:project:GetTypeScript", args ?? new GetTypeScriptArgs(), options.WithDefaults());

        public static Output<GetTypeScriptResult> Invoke(GetTypeScriptInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetTypeScriptResult>("supabase:project:GetTypeScript", args ?? new GetTypeScriptInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTypeScriptArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the project
        /// </summary>
        [Input("projectId")]
        public string? ProjectId { get; set; }

        public GetTypeScriptArgs()
        {
        }
    }

    public sealed class GetTypeScriptInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of the project
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        public GetTypeScriptInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetTypeScriptResult
    {
        /// <summary>
        /// TypeScript types of the project
        /// </summary>
        public readonly string Types;

        [OutputConstructor]
        private GetTypeScriptResult(string types)
        {
            Types = types;
        }
    }
}
