# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'FunctionStatus',
    'Plan',
    'Region',
]


class FunctionStatus(str, Enum):
    ACTIVE = "ACTIVE"
    REMOVED = "REMOVED"
    THROTTLED = "THROTTLED"


class Plan(str, Enum):
    FREE = "free"
    PRO = "pro"


class Region(str, Enum):
    US_EAST1 = "us-east-1"
    US_WEST1 = "us-west-1"
    AP_SOUTHEAST1 = "ap-southeast-1"
    AP_NORTHEAST1 = "ap-northeast-1"
    AP_NORTHEAST2 = "ap-northeast-2"
    AP_SOUTHEAST2 = "ap-southeast-2"
    EU_WEST1 = "eu-west-1"
    EU_WEST2 = "eu-west-2"
    EU_CENTRAL1 = "eu-central-1"
    CA_CENTRAL1 = "ca-central-1"
    AP_SOUTH1 = "ap-south-1"
    SA_EAST1 = "sa-east-1"
