# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .function import *
from .get_type_script import *
from .organization import *
from .project import *
from .provider import *
from .secret import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_supabase.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_supabase.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "supabase",
  "mod": "index",
  "fqn": "pulumi_supabase",
  "classes": {
   "supabase:index:Function": "Function",
   "supabase:index:Organization": "Organization",
   "supabase:index:Project": "Project",
   "supabase:index:Secret": "Secret"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "supabase",
  "token": "pulumi:providers:supabase",
  "fqn": "pulumi_supabase",
  "class": "Provider"
 }
]
"""
)
