# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .organization import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_supabase.config as __config
    config = __config
    import pulumi_supabase.organization as __organization
    organization = __organization
    import pulumi_supabase.project as __project
    project = __project
else:
    config = _utilities.lazy_import('pulumi_supabase.config')
    organization = _utilities.lazy_import('pulumi_supabase.organization')
    project = _utilities.lazy_import('pulumi_supabase.project')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "supabase",
  "mod": "index",
  "fqn": "pulumi_supabase",
  "classes": {
   "supabase:index:Organization": "Organization"
  }
 },
 {
  "pkg": "supabase",
  "mod": "organization",
  "fqn": "pulumi_supabase.organization",
  "classes": {
   "supabase:organization:Project": "Project"
  }
 },
 {
  "pkg": "supabase",
  "mod": "project",
  "fqn": "pulumi_supabase.project",
  "classes": {
   "supabase:project:Function": "Function",
   "supabase:project:Secret": "Secret"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "supabase",
  "token": "pulumi:providers:supabase",
  "fqn": "pulumi_supabase",
  "class": "Provider"
 }
]
"""
)
