// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const FunctionStatus = {
    Active: "ACTIVE",
    Removed: "REMOVED",
    Throttled: "THROTTLED",
} as const;

export type FunctionStatus = (typeof FunctionStatus)[keyof typeof FunctionStatus];

export const Plan = {
    Free: "free",
    Pro: "pro",
} as const;

export type Plan = (typeof Plan)[keyof typeof Plan];

export const Region = {
    UsEast1: "us-east-1",
    UsWest1: "us-west-1",
    ApSoutheast1: "ap-southeast-1",
    ApNortheast1: "ap-northeast-1",
    ApNortheast2: "ap-northeast-2",
    ApSoutheast2: "ap-southeast-2",
    EuWest1: "eu-west-1",
    EuWest2: "eu-west-2",
    EuCentral1: "eu-central-1",
    CaCentral1: "ca-central-1",
    ApSouth1: "ap-south-1",
    SaEast1: "sa-east-1",
} as const;

export type Region = (typeof Region)[keyof typeof Region];
