// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("supabase");

/**
 * Supabase server (https://api.supabase.com/v1/)
 */
export declare const server: string;
Object.defineProperty(exports, "server", {
    get() {
        return __config.get("server") ?? "https://api.supabase.com/v1/";
    },
    enumerable: true,
});

/**
 * Supabase auth token
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

