# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('supabase')


class _ExportableConfig(types.ModuleType):
    @property
    def server(self) -> str:
        """
        Supabase server (https://api.supabase.com/)
        """
        return __config__.get('server') or 'https://api.supabase.com/'

    @property
    def token(self) -> Optional[str]:
        """
        Supabase auth token
        """
        return __config__.get('token')

