// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Supabase server (https://api.supabase.com/v1/)
func GetServer(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "supabase:server")
	if err == nil {
		return v
	}
	return "https://api.supabase.com/v1/"
}

// Supabase auth token
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "supabase:token")
}
