// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./function";
export * from "./getTypeScript";
export * from "./organization";
export * from "./project";
export * from "./provider";
export * from "./secret";

// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { Function } from "./function";
import { Organization } from "./organization";
import { Project } from "./project";
import { Secret } from "./secret";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "supabase:index:Function":
                return new Function(name, <any>undefined, { urn })
            case "supabase:index:Organization":
                return new Organization(name, <any>undefined, { urn })
            case "supabase:index:Project":
                return new Project(name, <any>undefined, { urn })
            case "supabase:index:Secret":
                return new Secret(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("supabase", "index", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("supabase", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:supabase") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
